"""Step 4 - Dimension creation (schema 'dim')."""
from loguru import logger
from .base import BaseStep, StepResult


class DimensionStep(BaseStep):
    def execute(self, config: dict, context: dict) -> StepResult:
        table_name = config.get("table_name")
        if not table_name:
            return StepResult(False, message="No dimension table name configured.")

        dim_schema = context.get("dim_schema", "dim")
        ods_schema = context.get("ods_schema", "ods")
        source_table = config.get("source_ods_table")
        load_mode = config.get("load_mode", "insert")

        sql = self.generate_sql(config, ods_schema, dim_schema)

        if self.is_dry_run:
            logger.info(f"[DRY RUN] Dimension SQL preview:\n{sql[:500]}")
            return StepResult(True, message=f"[DRY RUN] Dimension '{table_name}' simulated")

        try:
            conn = self._get_connection()
            cursor = conn.cursor()

            # Create dim table if it doesn't exist
            ddl_sql = self._build_dim_ddl(config, dim_schema, table_name)
            cursor.execute(ddl_sql)
            conn.commit()

            # Execute load
            cursor.execute(sql)
            rows = cursor.rowcount
            conn.commit()
            conn.close()

            logger.info(f"Dimension load: {rows} rows → [{dim_schema}].[{table_name}]")
            return StepResult(True, rows=max(rows, 0),
                              message=f"Dimension '{table_name}' loaded ({load_mode})")
        except Exception as e:
            logger.error(f"Dimension load failed: {e}")
            return StepResult(False, message=str(e))

    def _build_dim_ddl(self, config: dict, schema: str, table: str) -> str:
        use_sk = config.get("use_surrogate_key", True)
        sk_col = config.get("surrogate_key_column", "sk_id")
        selected = config.get("selected_columns", [])

        parts = []
        if use_sk:
            parts.append(f"[{sk_col}] INT IDENTITY(1,1) NOT NULL")

        for col in selected:
            parts.append(f"[{col}] NVARCHAR(500) NULL")

        cols_ddl = ",\n  ".join(parts)
        pk_clause = f",\nCONSTRAINT [PK_{table}] PRIMARY KEY ([{sk_col}])" if use_sk else ""

        return f"""
IF OBJECT_ID('{schema}.{table}', 'U') IS NULL
BEGIN
    CREATE TABLE [{schema}].[{table}] (
      {cols_ddl}{pk_clause}
    )
END
"""

    def generate_sql(self, config: dict, ods_schema: str = "ods",
                      dim_schema: str = "dim") -> str:
        table_name = config.get("table_name", "dim_table")
        source_table = config.get("source_ods_table", "ods_table")
        load_mode = config.get("load_mode", "insert")
        use_sk = config.get("use_surrogate_key", True)
        sk_col = config.get("surrogate_key_column", "sk_id")
        business_keys = config.get("business_key_columns", [])
        tracked_cols = config.get("tracked_columns", [])
        selected_cols = config.get("selected_columns", [])

        if load_mode == "insert":
            return self._generate_insert_sql(
                source_table, table_name, ods_schema, dim_schema,
                selected_cols, use_sk, sk_col
            )
        else:
            return self._generate_merge_sql(
                source_table, table_name, ods_schema, dim_schema,
                selected_cols, business_keys, tracked_cols, use_sk, sk_col
            )

    def _generate_insert_sql(self, source, target, src_schema, tgt_schema,
                               cols, use_sk, sk_col) -> str:
        col_list = ", ".join(f"[{c}]" for c in cols)
        return f"""-- ============================================================
-- Dimension Load (INSERT): [{tgt_schema}].[{target}]
-- Source: [{src_schema}].[{source}]
-- Generated by ETL Manager
-- ============================================================

INSERT INTO [{tgt_schema}].[{target}] (
  {col_list}
)
SELECT
  {col_list}
FROM [{src_schema}].[{source}] src
WHERE NOT EXISTS (
  SELECT 1 FROM [{tgt_schema}].[{target}] dim
  WHERE dim.[{cols[0] if cols else 'id'}] = src.[{cols[0] if cols else 'id'}]
);
"""

    def _generate_merge_sql(self, source, target, src_schema, tgt_schema,
                              cols, bk_cols, tracked_cols, use_sk, sk_col) -> str:
        on_clause = " AND ".join(
            f"target.[{k}] = source.[{k}]" for k in bk_cols
        ) or "1=0"
        update_set = ",\n    ".join(
            f"target.[{c}] = source.[{c}]" for c in tracked_cols
        ) or "target.[updated] = GETDATE()"
        col_list = ", ".join(f"[{c}]" for c in cols)
        src_col_list = ", ".join(f"source.[{c}]" for c in cols)

        return f"""-- ============================================================
-- Dimension Load (MERGE/UPSERT): [{tgt_schema}].[{target}]
-- Source: [{src_schema}].[{source}]
-- Business Key(s): {', '.join(bk_cols)}
-- Generated by ETL Manager
-- ============================================================

MERGE [{tgt_schema}].[{target}] AS target
USING (
    SELECT {col_list}
    FROM [{src_schema}].[{source}]
) AS source
ON ({on_clause})
WHEN MATCHED THEN
    UPDATE SET
    {update_set}
WHEN NOT MATCHED BY TARGET THEN
    INSERT ({col_list})
    VALUES ({src_col_list});
"""
