"""Step 5 - Fact table creation."""
from loguru import logger
from .base import BaseStep, StepResult


class FactStep(BaseStep):
    def execute(self, config: dict, context: dict) -> StepResult:
        table_name = config.get("table_name")
        if not table_name:
            return StepResult(False, message="No fact table name configured.")

        fact_schema = context.get("fact_schema", "fait")
        ods_schema = context.get("ods_schema", "ods")

        sql = self.generate_sql(config, ods_schema, fact_schema)

        if self.is_dry_run:
            return StepResult(True, message=f"[DRY RUN] Fact '{table_name}' simulated")

        try:
            conn = self._get_connection()
            cursor = conn.cursor()
            cursor.execute(sql)
            rows = cursor.rowcount
            conn.commit()
            conn.close()
            logger.info(f"Fact load: {rows} rows → [{fact_schema}].[{table_name}]")
            return StepResult(True, rows=max(rows, 0),
                              message=f"Fact table '{table_name}' loaded")
        except Exception as e:
            logger.error(f"Fact load failed: {e}")
            return StepResult(False, message=str(e))

    def generate_sql(self, config: dict, ods_schema: str = "ods",
                      fact_schema: str = "fait") -> str:
        table_name = config.get("table_name", "fact_table")
        source_table = config.get("source_ods_table", "ods_table")
        joins = config.get("joins", [])
        selected_cols = config.get("selected_columns", [])
        load_mode = config.get("load_mode", "insert")

        # Build JOIN clauses
        join_clauses = []
        select_extras = []
        for j in joins:
            dim_schema = j.get("dimension_schema", "dim")
            dim_table = j.get("dimension_table", "")
            alias = j.get("alias") or f"dim_{dim_table}"
            sk_col = j.get("surrogate_key_column", "sk_id")
            join_keys = j.get("join_keys", [])

            on_parts = " AND ".join(
                f"src.[{k['source']}] = {alias}.[{k['dimension']}]"
                for k in join_keys
            )
            if on_parts:
                join_clauses.append(
                    f"LEFT JOIN [{dim_schema}].[{dim_table}] {alias}\n"
                    f"  ON {on_parts}"
                )
                select_extras.append(f"{alias}.[{sk_col}] AS [{alias}_{sk_col}]")

        # Build SELECT
        select_parts = [f"src.[{c}]" for c in selected_cols] + select_extras
        select_clause = ",\n    ".join(select_parts) if select_parts else "src.*"
        join_clause = "\n".join(join_clauses)

        return f"""-- ============================================================
-- Fact Table Load: [{fact_schema}].[{table_name}]
-- Source: [{ods_schema}].[{source_table}]
-- Dimensions joined: {len(joins)}
-- Generated by ETL Manager
-- ============================================================

IF OBJECT_ID('{fact_schema}.{table_name}', 'U') IS NOT NULL
    TRUNCATE TABLE [{fact_schema}].[{table_name}];

INSERT INTO [{fact_schema}].[{table_name}]
SELECT
    {select_clause}
FROM [{ods_schema}].[{source_table}] src
{join_clause};
"""
