"""Step 2 - Staging load (schema 'sta')."""
from typing import Dict, Any, List
import pandas as pd
from loguru import logger
from .base import BaseStep, StepResult


class StagingStep(BaseStep):
    def execute(self, config: dict, context: dict) -> StepResult:
        table_name = config.get("table_name")
        if not table_name:
            return StepResult(False, message="No staging table name configured.")

        staging_schema = context.get("staging_schema", "sta")
        df: pd.DataFrame = context.get("dataframe")
        if df is None:
            return StepResult(False, message="No data in context (run ingestion first).")

        selected_columns = config.get("selected_columns") or list(df.columns)
        df = df[selected_columns].copy()
        batch_size = config.get("batch_size", 1000)
        truncate = config.get("truncate_before_load", True)

        if self.is_dry_run:
            logger.info(f"[DRY RUN] Would load {len(df)} rows into [{staging_schema}].[{table_name}]")
            context["staging_table"] = f"{staging_schema}.{table_name}"
            context["staging_dataframe"] = df
            return StepResult(True, rows=len(df), message="[DRY RUN] Staging load simulated")

        try:
            conn = self._get_connection()
            cursor = conn.cursor()

            # Build DDL - all VARCHAR(4000) for staging
            cols_ddl = ",\n  ".join(
                f"[{col}] VARCHAR(4000) NULL" for col in df.columns
            )
            self._drop_and_create_table(staging_schema, table_name, cols_ddl, conn)
            logger.info(f"Created [{staging_schema}].[{table_name}]")

            # Bulk insert in batches
            placeholders = ", ".join(["?"] * len(df.columns))
            col_names = ", ".join(f"[{c}]" for c in df.columns)
            insert_sql = (
                f"INSERT INTO [{staging_schema}].[{table_name}] ({col_names}) "
                f"VALUES ({placeholders})"
            )
            total_inserted = 0
            for i in range(0, len(df), batch_size):
                batch = df.iloc[i:i + batch_size]
                rows = [tuple(r) for r in batch.values]
                cursor.executemany(insert_sql, rows)
                conn.commit()
                total_inserted += len(rows)
                logger.debug(f"Inserted batch {i // batch_size + 1}: {total_inserted}/{len(df)} rows")

            conn.close()
            context["staging_table"] = f"{staging_schema}.{table_name}"
            context["staging_dataframe"] = df
            logger.info(f"Staging load complete: {total_inserted:,} rows → [{staging_schema}].[{table_name}]")
            return StepResult(True, rows=total_inserted,
                              message=f"Loaded {total_inserted:,} rows into staging")
        except Exception as e:
            logger.error(f"Staging load failed: {e}")
            return StepResult(False, message=str(e))

    def generate_sql(self, config: dict, schema: str = "sta") -> str:
        """Generate the staging load SQL for documentation."""
        table_name = config.get("table_name", "staging_table")
        columns = config.get("selected_columns", [])
        cols_ddl = "\n  ".join(f"[{c}] VARCHAR(4000) NULL," for c in columns)
        return f"""-- ============================================================
-- Staging Load: [{schema}].[{table_name}]
-- Generated by ETL Manager
-- ============================================================

IF OBJECT_ID('{schema}.{table_name}', 'U') IS NOT NULL
    DROP TABLE [{schema}].[{table_name}];

CREATE TABLE [{schema}].[{table_name}] (
  {cols_ddl.rstrip(',')}
);

-- Data loaded via Python bulk insert
"""
